### ISSUE TITLE
checkRevoked?

### ISSUE THREAD

**Issue by Molnfront** [Enkel-Digital/firebase-auth-express-middleware#7]
Is there a way to check revoked in the authz? https://firebase.google.com/docs/auth/admin/manage-sessions#revoke_refresh_tokens

I can do it with the Firebase admin SDK, but then I have to mess with the token again:

````
// Verify the ID token while checking if the token is revoked by passing
// checkRevoked true.
let checkRevoked = true;
getAuth()
  .verifyIdToken(idToken, checkRevoked)
  .then((payload) => {
    // Token is valid.
  })
  .catch((error) => {
    if (error.code == 'auth/id-token-revoked') {
      // Token has been revoked. Inform the user to reauthenticate or signOut() the user.
    } else {
      // Token is invalid.
    }
  });
````

**Comment by Jaimeloeuf** [comment]
Hi @Molnfront thanks for bringing this up, I just released a new patch version `1.0.10` that includes support for this.

To check if token is revoked, pass in `checkRevoked: true` in the options object. See example below
```javascript
app.use(authMiddleWare.authn(firebaseAuth, {
    checkRevoked: true,
}));
```

However do note that by doing this, every single request that comes in will cause your server to make an API call to the firebase auth server, thus increasing the latency of your application, and potentially increase cost due to the increased network traffic.

My suggestion if you were to use this, is to run your server on any Google Cloud Platform IaaS or PaaS, so that the network call to firebase auth server will be routed as internal network traffic making it much faster than calling it over the public internet if you were to use another cloud provider.
